### ISSUE TITLE
UI issues with new bulk request flow

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#849] opened 2021-03-23 17:37 UTC
**What Happened**
Two issues. In the bulk request studies flow, the "Continue" button disappears. When selecting or deselecting the checkbox for each location's card, the view jumps to the top.

**What Should Happen**
Control buttons should not disappear. The view shouldn't jump up/down when selecting/deselecting a card from the list of locations (intersections or midblocks).

**To Reproduce**
- Firefox, 86.0.1
- Full screen on primary 24" monitor (not laptop screen)

Steps to reproduce the bug:
1. Create a bulk selection for [King/Sumach to King/River to Gerrard/River](https://move.intra.prod-toronto.ca/view/location/s1:AwFvmBq-umBUdumB/CORRIDOR) (or just use this link!)
2. Select "Request New"
3. Authenticate if needed
4. On the "Select intersections" step, deselect all locations
5. Select checkbox beside King St E / Sumach St
6. Scroll down to King St E / River St / Lower River St
7. Select the checkbox beside that location
8. See first error -- the scrollable part of the drawer jumps to the top
9. Select "Continue"
10. See second error -- the bar with the buttons disappears, and the page is still on the first step of the bulk request flow, "Select intersections"

**Screenshots**
No console or network errors.

Before selecting "Continue"
![Screenshot 2021-03-23 132900](https://user-images.githubusercontent.com/3179624/112191301-41ec4000-8bdc-11eb-9396-aab74955a172.png)

After selecting "Continue"
![Screenshot 2021-03-23 132912](https://user-images.githubusercontent.com/3179624/112191707-a9a28b00-8bdc-11eb-81ef-1f377614bd45.png)

**Additional Notes**
This issue isn't happening in Chrome Version 89.0.4389.90 (Official Build) (64-bit).
Couldn't test in Edge because I'm still having the blank-screen problem with Edge.

**Comment by mkewins** [comment] 2021-03-23 17:38
@jwrcoleman - fyi

**Comment by candu** [comment] 2021-05-12 19:45
Confirmed that this is still occurring in Firefox with MOVE v1.3.2; fix slated for v1.5 release.  (It looks like a one-line change in `ReportCollisionDirectory`...)

**Comment by candu** [comment] 2021-05-28 18:25
This appears to have been fixed by recent work on study request management - marking closed.

**Comment by candu** [comment] 2021-06-01 17:54
Seems to be resolved in New Request, but _not_ in Edit Request - reopening to fix that.

**Closed** 2021-06-08 17:54 UTC
Labels: bug, p2
